# -*- coding: utf-8 -*-
"""Random.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1deNrjKIj2ierI8czlZ3TAOsmfWZXLxzd
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report
)
data_path = "/content/drive/MyDrive/IMDB Dataset.csv"
df = pd.read_csv(data_path)

print("Dataset Shape:", df.shape)
print(df.head())
X = df['review']
y = df['sentiment'].map({'positive': 1, 'negative': 0})
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
X_train = vectorizer.fit_transform(X_train_text)
X_test = vectorizer.transform(X_test_text)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("\nRandom Forest Performance:")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}\n")

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Negative','Positive']))
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='magma', cbar=True,
            xticklabels=['Negative','Positive'], yticklabels=['Negative','Positive'])
plt.xlabel('Predicted', fontsize=12)
plt.ylabel('Actual', fontsize=12)
plt.title('Confusion Matrix - Random Forest', fontsize=14)
plt.show()
metrics_dict = {"Accuracy": accuracy, "Precision": precision, "Recall": recall, "F1-score": f1}

plt.figure(figsize=(8,5))
colors = ['#00CED1', '#9400D3', '#FFD700', '#FF4500']
sns.barplot(x=list(metrics_dict.keys()), y=list(metrics_dict.values()), palette=colors)
plt.ylim(0, 1.1)
plt.title("Random Forest Performance Metrics", fontsize=14)
plt.ylabel("Score", fontsize=12)
plt.xlabel("Metric", fontsize=12)
for i, v in enumerate(metrics_dict.values()):
    plt.text(i, v + 0.02, f"{v:.2f}", ha='center', fontsize=11)

plt.show()
rf_model_path = "/content/drive/MyDrive/random_forest_model.pkl"
joblib.dump(rf_model, rf_model_path)